spring:
  application:
    name: dev-profile-api
    
  security:
    user:
      name: admin
      password: password
      roles: ADMIN
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23limyiaaUfEltQZAO
            client-secret: e063625aeeccd6f86644810901cf7c7ba88b59c1
            scope: read:user
  
  datasource:
    url: jdbc:h2:mem:devprofiledb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect